openapi: "3.0.0"
info:
  description: "Demo Contact API"
  version: "1.0.0"
  title: "Contacts API"
  termsOfService: "http://swagger.io/terms/"

servers:
  - url: /v1
    description: server

components:
  securitySchemes:
    basic:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic
      x-basicInfoFunc: app.basic_auth


paths:
  /users:
    get:
      operationId: contact.create_testuser
      summary: Creates a user.
      responses:
        '200':    # status code
          description: Create a user

  /contact:
    get:
      operationId: contact.read_contact
      summary: Returns a list of Contacts.
      responses:
        '200':    # status code
          description: A JSON array of user contacts
          content:
            application/json:
              schema: 
                type: object
                properties:
                  name:
                    type: string
                  contact:
                    type: string
                items: 
                  type: string
                  
    post:
      operationId: contact.create
      summary: Create a contact.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name: 
                  type: string
                contact:
                  type: string
              required:
                - name
                - contact
      responses:
        '201':
          description: Successfully created contact.
        '401': 
            description: Unauthorized
      security:
        - basic: []
  
  /contact/{id}:        
    put:
      operationId: contact.update
      summary: Update a contact
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                contact:
                  type: string
              required:
                - contact
                
      responses:
        '201':
          description: Contact Updated
        '401': 
            description: Unauthorized
        '403':
          description: Unauthorized
        '404':
          description: Not Found
      security:
        - basic: []
  
    delete:
      operationId: contact.delete
      parameters:
        - name: id
          in: path
          required: true
          schema: 
            type: integer
      summary: Delete a contact
      responses:
        '200':
          description: Contact Delete
        '401': 
            description: Unauthorized
        '404': 
          description: Not Found
        '403': 
          description: Unauthorized
      security:
        - basic: []
  